name: All Browsers in Parallel - End-to-end tests
on:
  push:
  workflow_dispatch:
jobs:
  cypress-run-chrome:
    runs-on: ubuntu-22.04
    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v4
      - name: Step 2 - Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
      - name: Step 3 - Roda o report
        continue-on-error: true
        run: |
          npx mochawesome-merge ./mochawesome-report/*.json > mochawesomeReport_Chrome.json && npx marge ./mochawesomeReport_Chrome.json
          ls -la mochawesome-report/
      - name: 游꾸 Step 4 - mochawesome-report.html
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: report-tests-chrome
          path: mochawesome-report/
  cypress-run-firefox:
    runs-on: ubuntu-22.04
    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v4
      - name: Step 2 - Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: firefox
      - name: Step 3 - Roda o report
        continue-on-error: true
        run: |
          npx mochawesome-merge ./mochawesome-report/*.json > mochawesomeReport_Firefox.json && npx marge ./mochawesomeReport_Firefox.json
          ls -la mochawesome-report/
      - name: 游꾸 Step 4 - mochawesome-report.html
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: report-tests-firefox
          path: mochawesome-report/
  cypress-run-edge:
    runs-on: ubuntu-22.04
    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v4
      - name: Step 2 - Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: edge
      - name: Step 3 - Roda o report
        continue-on-error: true
        run: |
          npx mochawesome-merge ./mochawesome-report/*.json > mochawesomeReport_Edge.json && npx marge ./mochawesomeReport_Edge.json
          ls -la mochawesome-report/
      - name: 游꾸 Step 4 - mochawesome-report.html
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: report-tests-edge
          path: mochawesome-report/
  cypress-run-safari:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install webkit dependencies for Linux
        run: npx playwright install-deps webkit
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          command: npx cypress run --browser webkit
      - name: Step 3 - Roda o report
        continue-on-error: true
        run: |
          npx mochawesome-merge ./mochawesome-report/*.json > mochawesomeReport_Webkit.json && npx marge ./mochawesomeReport_Webkit.json
          ls -la mochawesome-report/
      - name: 游꾸 Step 4 - mochawesome-report.html
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: report-tests-webkit
          path: mochawesome-report/
  cypress-run-electron:
    runs-on: ubuntu-22.04
    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v4
      - name: Step 2 - Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: electron
      - name: Step 3 - Roda o report
        continue-on-error: true
        run: |
          npx mochawesome-merge ./mochawesome-report/*.json > mochawesomeReport_Electron.json && npx marge ./mochawesomeReport_Electron.json
          ls -la mochawesome-report/
      - name: 游꾸 Step 4 - mochawesome-report.html
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: report-tests-electron
          path: mochawesome-report/
