name: Chrome/Allure - End-to-end tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
permissions: write-all

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Step 1 Install dependencies
      run: |
        npm install -g allure-commandline --save-dev |
        npm install
    
    - name: Step 2 Cypress run - browser chrome
      uses: cypress-io/github-action@v6
      if: always()
      continue-on-error: true
      with:
        spec: cypress/e2e/features/**/*.cy.*
        env:  allure=true, video=false
        browser: chrome
        headed: true

    - name: Generate Allure report
      run: npm run allure:generate

    - name: Load test report history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        gh_pages: gh-pages
        allure_history: allure-history
        allure_results: allure-results

    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history
        allow_empty_commit: true
        force_orphan: true
